name: Secret Scan with Gitleaks (Official Action)

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Gitleaks (Scan Only Changed Code)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --exit-code 1 --report-path=gitleaks-report.json

      - name: Upload Report (on Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
