name: Secret Scan (Block Build on Secret Detection)

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

jobs:
  gitleaks-scan:
    name: Run Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
          | grep "browser_download_url.*linux.*amd64" \
          | cut -d : -f 2,3 \
          | tr -d \" | wget -qi -
          chmod +x gitleaks* && mv gitleaks* /usr/local/bin/gitleaks

      - name: Run Gitleaks (Scan Only New Code)
        run: |
          gitleaks detect \
            --source . \
            --no-git \
            --report-path gitleaks-report.json \
            --exit-code 1

      - name: Upload Gitleaks Report (if scan fails)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
